### ISSUE TITLE
Logo Design for  node currency converter

### ISSUE THREAD

**Issue by zuurw** [acifani/node-currency-converter#10]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by acifani** [comment]
Hey @zuurw, yeah, sure thing! I'd love it. Anything I can help you with?

**Comment by zuurw** [comment]
Hi @acifani, I create some designs for node-currency-converter, so I was trying to create something with arrows that represent convertion, and I try to create the letter N as a reference to node.
See if you like one of this designs, if not I can make a new one.

Greetings

![node](https://user-images.githubusercontent.com/40801473/49044936-3e407e00-f1c7-11e8-944c-bdb6468bb002.jpg)

**Comment by acifani** [comment]
These all look fantastic @zuurw ! Thanks a lot for the work and effort you put in.
I'm loving the left one on the center row. What do you think?

**Comment by zuurw** [comment]
Hi @acifani,

Sorry for the late answerd, Im going to send the files for the logo that you pick.
I will send png and other editable files.

I will send a pull request with that.

Thank You!
